version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-57-db
    restart: always
    tty: true
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./dump:/dump
    environment:
      MYSQL_ROOT_PASSWORD: "root"
